prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix : <http://id.melindax.local/ns/marc/>

insert {
    ?coll skos:member ?term .
} where {
    ?coll a :CollectionClass .
    ?term a ?coll .
}
